---
- hosts: localhost
  become: true
  connection: local
  vars:
  roles:
  tasks:
    - name: Updating APK Cache
      apk:
        update_cache: yes

    - name: Installing Pre-Reqs
      apk:
        name: "{{ item }}"
        state: "present"
      with_items:
        - 'rsyslog'
        - 'supervisor'

    - name: setting Debian facts
      set_fact:
        apache2_log_dir: "/var/log/apache2"
        apache2_web_group: "www-data"
        apache2_web_owner: "www-data"
        apache2_web_root: "/var/www/html"
      when: ansible_os_family == "Debian"

    - name: setting PHP version
      set_fact:
        php_path: 'etc/php5'  #no leading / for template path
        php_ver: 5
      when: >
            ansible_distribution == "Debian" or
            (ansible_distribution == "Ubuntu" and
            ansible_distribution_version <= '14.04')

    - name: setting PHP version
      set_fact:
        php_path: 'etc/php/7.0'  #no leading / for template path
        php_ver: 7.0
      when: >
            (ansible_distribution == "Ubuntu" and
            ansible_distribution_version >= '16.04')

    - name: Installing Apache2
      apk:
        name: "apache2"
        state: "present"

    - name: Installing PHP
      apk:
        name: "php5-apache2"
        state: "present"
      when: >
            apache2_enable_php == "true"

    - name: Creating Folders
      file:
        path: "{{ item }}"
        state: "directory"
      with_items:
        - '/etc/supervisor.d'
        - '/run/apache2'
